ConArtist = "ConArtist"

"... You're in!" = "TODO: translate"
"{{}} conventions coming soon." = "{{}}博览会快来了"
"{1} convention coming soon." = "{一个}博览会快来了"
Account = "帐户"
Add = "添加"
Address = "地址"
All = "所有"
Amount = "费用"
"An unknown error has occurred" = "出现未知错误"
Any = "每个"
"And again" = "… 再次"
Average = "平均"
Back = "回去"
"Can I get your email?" = "你会告诉我你的电子邮件吗？"
Cancel = "取消"
Category = "类别"
Change = "更改"
"Change Currency" = "更改货币"
"Change Email" = "更改电子邮件"
"Change Language" = "更改语言"
"Change Name" = "更改名字"
"Change Password" = "更改密码"
Completed = "过去"
"Confirm new email" = "确认新电子邮件"
"Confirm new password" = "确认新密码"
Continue = "继续"
Conventions = "博览会"
Currency = "货币"
"Currency changed successfully" = "TODO: translate"
"Current earnings" = "TODO: translate"
"Current password" = "当前密码"
Customers = "顾客"
Dashboard = "仪表板"
Dates = "日期"
Delete = "删除"
Details = "细节"
Discard = "放弃"
Downvote = "没有帮助"
Edit = "编辑"
"Editing Expense" = "编辑费用"
"Editing Sale" = "编辑销售"
Email = "电子邮件"
"Ensure the format above matches your data" = "TODO: translate"
Expenses = "费用"
Export = "出口"
"Export Products" = "出口产品"
"Extra info" = "TODO: translate"
"Filter types" = "TODO: translate"
Finish = "完成"
"Forgot Password" = "忘记密码"
General = "通用"
Grouping = "TODO: translate"
Hours = "营业时间"
"How much do these cost?" = "这些多少钱？"
"How many" = "几个?"
"Huh?" = "什么？"
"I forgot my password" = "我忘记我的密码"
"I have read and agree to the {Terms of Service} and {Privacy Policy}" = "我已经阅读并同意{Terms of Service}和{Privacy Policy}"
ID = "ID"
Import = "进口"
"Import failed: Cannot change the type of {}" = "TODO: translate {}"
"Import failed: Could not find product type named {}" = "TODO: translate {}"
"Import failed: Could not find product with id {}" = "TODO: translate {}"
"Import failed: Failed to save products. Please try again later!" = "TODO: translate"
"Import failed: Unknown error" = "TODO: translate"
"Import Products" = "进口产品"
"Importing only {}" = "只进口{}"
"Include IDs" = "包含ID"
"Include IDs to modify exisiting products. New products can be left with an empty ID." = "TODO: translate"
"Include titles" = "包括标题"
"Includes titles" = "包括标题"
"Including IDs makes it much easier to import your products again later!" = "TODO: translate"
"Includes IDs" = "包含ID"
Info = "信息"
Inventory = "库存"
"It seems something went wrong." = "TODO: translate"
"Keep it short and sweet!" = "不要太长了！"
Language = "语言"
"Language changed successfully" = "语言改变成功了"
"Language & Location" = "语言和地方"
"Let's get started!" = "开始了"
"Loading..." = "载入中…"
"Looks good to me" = "在我看来很好"
"Make a suggestion" = "提个建议"
"Manage Prices" = "管理价格"
"Manage Products" = "管理产品"
"Manage Product Types" = "TODO: translate"
Metric = "TODO: translate"
"{} minutes" = "{}分钟"
Mode = "模式"
Money = "钱"
Name = "名字"
"Name changed successfully" = "名字改变成功了"
"Net profit" = "净利"
"New email" = "新的电子邮件"
"New expense" = "添加费用"
"New Expense" = "新的费用"
"New name" = "新的名字"
"New password" = "新的密码"
"New product type" = "TODO: translate"
"New Product Type" = "TODO: translate"
"New product" = "新产品"
"New Product" = "新产品"
"New sale" = "添加销售"
"New Sale" = "新的销售"
"No activity for this day" = "TODO: translate"
"No conventions today" = "今天没有博览会"
"No conventions upcoming" = "TODO: translate"
"No products yet... add one!" = "TODO: translate"
Note = "注意"
"Nothing to say..." = "没有"
"Now just sign at the bottom." = "现在就在这里签名"
"Oh no..." = "不好了…"
Options = "选项"
Password = "密码"
"Password changed successfully" = "密码改变成功了"
"Pick a password. I'm not looking." = "选一个密码。我没看。"
Price = "价钱"
Prices = "价钱"
Product = "产品"
"Product type is specified as a column" = "TODO: translate"
"Product types will be split into different files" = "TODO: translate"
"Product types will be included in each row" = "TODO: translate"
Products = "产品"
"Products imported successfully" = "TODO: translate"
"Promise." = "我承诺。"
Quantity = "多少"
Recommend = "推荐"
Remaining = "其余"
Reorder = "改组"
"Report a bug/Request a feature" = "提个建议"
"Reset Password" = "重设密码"
Revenue = "收入"
Sales = "销售"
"Other Sales" = "别的销售"
Sale = "销售"
"Sales By Type" = "TODO: translate"
"Sales Over Time" = "TODO: translate"
Save = "存储"
Search = "搜索"
"See all" = "查看全部"
"Separate types" = "TODO: translate"
Settings = "设置"
"Share Info" = "提供信息"
"Sign in" = "登录"
"Sign out" = "登出"
"Sign up" = "注册"
"Sign Up" = "注册"
SKU = "货号"
Sold = "买了"
"Some actions might not have been saved. Please try again later" = "TODO: translate"
"Something is wrong..." = "TODO: translate"
Stats = "TODO: translate"
Suggestions = "建议"
Support = "联系支持"
"Thanks for your feedback!" = "感谢您的反馈意见！"
"That email is already being used" = "该电子邮件已被使用"
"There are no suggestions yet. Feel free to make a request!" = "现在没有建议。TODO: translate"
"There's nothing here..." = "这里什么都没有"
"This has to be a whole number!" = "TODO: translate"
"This isn't a number!" = "这不是数字"
"This name is used twice!" = "这个名字重复了"
"This page is coming soon!" = "快来了"
"This quantity is set twice!" = "这个数量重复了"
Time = "时候"
Today = "今天"
"Today's hours" = "今天的时间"
Total = "总收入"
Type = "TODO: translate"
"Uh oh. You have been logged out!" = "TODO: translate"
Unknown = "未知"
Upcoming = "即将到来"
Upvote = "有帮助"
"Use lots of details. Make sure we know what you want!" = "TODO: translate"
"View on map" = "看地图"
"View records" = "查看记录"
"We won't send you anything." = "我们不会向你发送任何东西。"
"We're glad you joined us." = "我们很高兴你加入了"
Website = "网站"
"Welcome back" = "欢迎回来"
"Working..." = "进行中…"
"What do people call you?" = "你叫什么？"
"You aren't selling any of these" = "TODO: translate"
"You can change this later" = "你可以稍后改变它"
"You can charge more than that!" = "TODO: translate"
"You can't have less than none!" = "TODO: translate"
"You can't sell none!" = "你不能卖0的"
"You don't have any conventions starred... Why don't you go find one you like?" = "TODO: translate"
"You haven't been to any conventions yet..." = "TODO: translate"
"You haven't set any prices yet" = "TODO: translate"
"You'll have to try again later... Sorry for the inconvenience." = "TODO: translate"
"Your changes were not saved. Please try again later" = "TODO: translate"
"Your email looks wrong" = "你的邮件看起来不对"
"Your emails don't match" = "您的电子邮件不匹配"
"Your name" = "您的名字"
"Your password is incorrect" = "您的密码不正确"
"Your password is too short" = "您的密码太短"
"Your passwords don't match" = "您的密码不匹配"
EEE = "EEE."
"EEEE MMMM d, yyyy" = "yyyy年MMMd日EEE"
"EEEE MMMM d, yyyy. h:mma" = "yyyy年MMMd日EEE, H:mm"
"MMMM d, yyyy. h:mma" = "yyyy年MMMd日, H:mm"
"MMM. d, yyyy" = "yyyy年MMMd日"
"h:mma" = "H:mm"
"h:mm" = "H:mm"
"{{}} {is today. Good luck!}" = "{{}}{是今天。加油！}"
"{} - {}" = "{} – {}"
"{} {} - {}" = "{} {} – {}"
"{}x" = "{}×"
"<Convention info contribution disclaimer>" = "TODO: translate"
"<Email usage disclaimer>" = "TODO: translate"
"<Empty prices list message>" = "TODO: translate"
"<Empty products list message>" = "TODO: translate"
"<First product type message>" = "TODO: translate"
"<Name usage disclaimer>" = "TODO: translate"
"<No convention user info>" = "TODO: translate"
"<Splash body>" = "TODO: translate"
"<Splash title>" = "TODO: translate"
"<Suggestion disclaimer>" = "TODO: translate"
"<Verify Account Successful>" = "TODO: translate"
"<Verify Account Failed>" = "TODO: translate"

# Language tags
en-ca = "English (Canada)"
en-us = "English (USA)"
zh-Hans = "中文 (简体)"

# General
"Load more" = "装载更多"
View = "看→"
City = "城市"
Country = "国家"
"Don't forget to verify your email!" = "TODO: translate"
"Resend verification email" = "TODO: translate"
"Advanced Search" = "TODO: translate"

# Dashboard
"Find more" = "TODO: translate"

# Sign in
"Stay signed in" = "TODO: translate"
"Sign up at conartist.app" = "在{action:conartist.app}上注册"

# Products/product types
"Delete this product?" = "Delete this product?"
"Delete this product type?" = "Delete this product type?"
"This cannot be undone" = "This cannot be undone"

# Convention search
Going = "参加"
"Not going" = "不参加"
"There are no conventions right now" = "现在没有博览会"
"<Convention search empty>" = "TODO: translate"

# Convention details
# Records
"<Empty records list message>" = "你还没有卖出任何东西"
"<Empty no-con records list message>" = "TODO: translate"
"Expense saved" = "TODO: traslate"
"Sale saved" = "TODO: translate"
"Sale deleted" = "TODO: translate"
"The amount cannot be zero" = "TODO: translate"
"The amount is invalid" = "TODO: translate"
Remove = "Remove"

# Settings
About = "TODO: translate"
"Privacy Policy" = "隐私政策"
"Terms of Service" = "服务条款"
Version = { ios = "版本: {light:{}}", web = "版本", android = "版本: {light:{}}" }
"Contact Support" = { ios = "联系支持: {light:{}}", web = "联系支持" }
"<Support description>" = "TODO: translate"
"Support Us on Ko-fi" = "在Ko-fi上支持我们"
Contribute = "有助于"
Donate = "捐款"
FAQ = "常问问题"
"Chat on Discord" = "TODO: translate"
"Download on the App Store" = "TODO: translate"
"Request a Convention" = "Request a Convention"
"Email: {}" = "电子邮件: {light:{}}"
"Verification email sent" = "TODO: translate"
"You should receive it shortly" = "TODO: translate"

# Errors
"You can't do that right now" = "TODO: translate"
"Maybe the convention has already started?" = "TODO: translate"
