title = "Ottawa Comiccon"
start_date = 2023-09-08
end_date = 2023-09-10
tags = []

[website]
title = "ottawacomiccon.com"
url = "https://ottawacomiccon.com/"

[address]
address = "EY Centre\n4899 Uplands Dr\nOttawa, ON K1V 2N6"
city = "Ottawa, ON"
country = "Canada"

[address.coordinates]
lat = 45.3970732
lon = -75.7497856
