ALTER TABLE Records
  ALTER COLUMN sale_time SET DEFAULT (TIMEZONE('utc'::TEXT, now()));
ALTER TABLE Records
  ALTER COLUMN sale_time TYPE TIMESTAMP WITHOUT TIME ZONE USING (sale_time::TIMESTAMPTZ::TIMESTAMP);
ALTER TABLE Expenses
  ALTER COLUMN spend_time SET DEFAULT (TIMEZONE('utc'::TEXT, now()));
ALTER TABLE Expenses
  ALTER COLUMN spend_time TYPE TIMESTAMP WITHOUT TIME ZONE USING (spend_time::TIMESTAMPTZ::TIMESTAMP);
