// flow-typed signature: 5b00bf0370d825cd205989f032999094
// flow-typed version: <<STUB>>/css-modules-flow-types-loader_v^1.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-modules-flow-types-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-modules-flow-types-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-modules-flow-types-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-modules-flow-types-loader/dist/index.js' {
  declare module.exports: $Exports<'css-modules-flow-types-loader/dist/index'>;
}
