// flow-typed signature: db4aa15e69b24a53f202195a98b8e1c1
// flow-typed version: <<STUB>>/save-as_v^0.1.8/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'save-as'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'save-as' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'save-as/lib/index' {
  declare module.exports: any;
}

declare module 'save-as/src/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'save-as/lib/index.js' {
  declare module.exports: $Exports<'save-as/lib/index'>;
}
declare module 'save-as/src/lib/index.js' {
  declare module.exports: $Exports<'save-as/src/lib/index'>;
}
