platform :ios, '10.3'

target 'ConArtist' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ConArtist
  pod 'Apollo', '~> 0.7.0'
  pod 'Alamofire', '~> 4.5'
  pod 'Gloss', '~> 2.0'
  pod 'Strongbox'
  pod 'SwiftMoment'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'SexyTooltip'
  pod 'MaterialComponents/Snackbar'
end
