platform :ios, '11.0'

target 'ConArtist' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ConArtist
  pod 'Apollo', '~> 0.7.0'
  pod 'Alamofire', '~> 4.5'
  pod 'Gloss', '~> 2.0'
  pod 'Strongbox'
  pod 'SwiftMoment'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'SexyTooltip'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
  pod 'PrettyString', '~> 0.1'
end
