title = "Geeked Out"
start_date = 2022-03-26
end_date = 2022-03-27

[website]
title = "www.geekedoutevents.ca"
url = "https://www.geekedoutevents.ca/"

[address]
address = "Nepean Sportsplex\n1701 Woodroffe Ave\nNepean, ON, Canada\nK2G 1W2"
city = "Ottawa, ON"
country = "Canada"

[address.coordinates]
lat = 45.3271152
lon = -75.7468782
