title = "Anime Toronto"
start_date = 2023-09-01
end_date = 2023-09-03

[website]
title = "animetoronto.ca"
url = "https://animetoronto.ca/"

[address]
address = "Metro Toronto Convention Centre\n255 Front St W\nToronto, ON, Canada\nM5V 2W6"
city = "Toronto, ON"
country = "Canada"

[address.coordinates]
lat = 43.6434157
lon = -79.3884683
