title = "FanExpo Canada"
start_date = 2024-08-22
end_date = 2024-08-25

[website]
title = "fanexpohq.com"
url = "https://fanexpohq.com/fanexpocanada/"

[address]
address = "Metro Toronto Convention Centre\n255 Front St W\nToronto, ON M5V 2W6\nCanada"
city = "Toronto, ON"
country = "Canada"

[address.coordinates]
lat = 43.643776
lon = -79.386986
