#! /bin/bash
apollo client:codegen \
  --endpoint=http://localhost:8080/api/v2 \
  --queries=../shared/graphql/**/*.graphql \
  --target=flow \
  --addTypename \
  --outputFlat \
  --watch \
  ./src/api/schema.js
