#! /bin/bash
apollo schema:download --endpoint=http://localhost:8080/api/v2 schema.json
apollo client:codegen ./src/api/schema.js --queries="$(find ../shared/graphql -name '*.graphql')" --target=flow --addTypename --outputFlat
rm schema.json
